defaults:
  lakefs_repo: data-raw
  lakefs_branch: main
  lakefs_commit_message: new version from RKI
  mariadb_database: episerve-raw-data
  run_daily: true

datasets:
  grippeweb:
    enabled: true
    deployment_name: download__grippeweb
    parameters:
      source_url: https://raw.githubusercontent.com/robert-koch-institut/GrippeWeb_Daten_des_Wochenberichts/refs/heads/main/GrippeWeb_Daten_des_Wochenberichts.tsv
      source_delimiter: "\t"
      local_path: /tmp/grippeweb.tsv
      lakefs_object_path: RAW/RKI/grippeweb.tsv
      mariadb_table: grippeweb

  corona_incidence_germany:
    enabled: true
    deployment_name: download__corona_incidence_germany
    parameters:
      source_url: https://raw.githubusercontent.com/robert-koch-institut/COVID-19_7-Tage-Inzidenz_in_Deutschland/refs/heads/main/COVID-19-Faelle_7-Tage-Inzidenz_Deutschland.csv
      source_delimiter: ","
      local_path: /tmp/covid_germany.tsv
      lakefs_object_path: RAW/RKI/covid_germany.tsv
      mariadb_table: corona_incidence_germany

  corona_incidence_states:
    enabled: true
    deployment_name: download__corona_incidence_states
    parameters:
      source_url: https://raw.githubusercontent.com/robert-koch-institut/COVID-19_7-Tage-Inzidenz_in_Deutschland/refs/heads/main/COVID-19-Faelle_7-Tage-Inzidenz_Bundeslaender.csv
      source_delimiter: ","
      local_path: /tmp/covid_states.tsv
      lakefs_object_path: RAW/RKI/covid_states.tsv
      mariadb_table: corona_incidence_states

  wastewater_surveillance_aggregate:
    enabled: true
    deployment_name: download__wastewater_surveillance_aggregate
    parameters:
      source_url: https://raw.githubusercontent.com/robert-koch-institut/Abwassersurveillance_AMELAG/refs/heads/main/amelag_aggregierte_kurve.tsv
      source_delimiter: "\t"
      local_path: /tmp/wastewater_surveillance_aggregate.tsv
      lakefs_object_path: RAW/RKI/wastewater_surveillance_aggregate.tsv
      mariadb_table: wastewater_surveillance_aggregate

  weather_berlin_daily:
    enabled: true
    deployment_name: download__weather_berlin_daily
    parameters:
      source_url: "https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&daily=temperature_2m_max,temperature_2m_min,temperature_2m_mean&past_days=10&format=csv&timezone=Europe%2FBerlin"
      source_delimiter: ","
      source_skiprows: 3
      local_path: /tmp/weather_berlin_daily.csv
      lakefs_object_path: RAW/open-meteo/weather_berlin_daily.csv
      lakefs_commit_message: new version from Open-Meteo
      mariadb_table: weather_berlin_daily
      mariadb_primary_key: time
